In [4]:
import numpy as np


In [5]:
my_List = [1,4,2,6]
arr = np.array(my_List)
print(arr)
# this is the way to create array in Python by making use of list data structure

[1 4 2 6]


In [6]:
# this is the way to create 2D array
my_lst = [2,5,3,1]
my_lst2 = [5,0,1,3]
my_lst3 = [3,6,9,1]

arr2 = np.array([my_lst,my_lst2,my_lst3])
print(arr2)

[[2 5 3 1]
 [5 0 1 3]
 [3 6 9 1]]


In [7]:
# We can also chack the size or shape of the array

arr2.shape
# this shows whats the size of the array ie. it has 3 rows and 4 cols

(3, 4)

In [8]:
# we can also reshape it by using reshape inbuilt function

arr2.reshape(6,2)

# total number of elements should not exceed 12 because 3x4 this will give you total number of elements

array([[2, 5],
       [3, 1],
       [5, 0],
       [1, 3],
       [3, 6],
       [9, 1]])

In [9]:
import numpy as np

# this is the way to create 2D array
my_lst = [2,5,3,1]
my_lst2 = [5,0,1,3]
my_lst3 = [3,6,9,1]

arr2 = np.array([my_lst,my_lst2,my_lst3])

# we can also reshape it into like this
arr2.reshape(1,12)

array([[2, 5, 3, 1, 5, 0, 1, 3, 3, 6, 9, 1]])

In [10]:
arr2.reshape(3,4)

array([[2, 5, 3, 1],
       [5, 0, 1, 3],
       [3, 6, 9, 1]])

In [11]:
arr2[0:2, 0:2]

array([[2, 5],
       [5, 0]])

In [12]:
arr2[1:3 , 2:4]

array([[1, 3],
       [9, 1]])

In [13]:
arr2[1:2,1:]

array([[0, 1, 3]])

In [14]:
# arange function inbuilt function
arr = np.arange(0,21)
arr
# using this we are able to get all the numbers between 0 to 20.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [15]:
# arange function has 3 parameters 1) start 2) stop 3) step
# step - tells us how many elements to skip till the end
arr = np.arange(0,31,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [17]:
# Almost same as arange only diff is it has 3rd paramter where it define how many division you want.

np.linspace(1,5, 20)


array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [20]:
# ones() this is a inuilt function that will give array that contains all 1's in it
# also we can change the datatype of 1's that we are getting
# Eg ) np.ones(4, dtype = int)

np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
# np.random.rand this is also an inbuilt function that takes a dimension and then creates an array for us between 0 and 1
# now these are random values whenever i run this again then the values will get changed as it is a random distribution
np.random.rand(4,3)

array([[0.71126469, 0.05618668, 0.63360517],
       [0.07457753, 0.43165679, 0.96408857],
       [0.52650842, 0.52121841, 0.25257428],
       [0.00610628, 0.64980904, 0.90502432]])

In [26]:


# np.random.randint(0,100,9) this is function that selects 9 numbers between 0-100 randomly everytime you run this code.


np.random.randint(10,90, 9)

array([56, 83, 64, 15, 39, 73, 10, 39, 55])